src/cron/cron.service.ts
src/ventas/discounts/discounts.controller.ts
src/ventas/discounts/discounts.service.ts
tsconfig.json

feat: :bug: bug repository

---

src/reports/reports.service.ts

style: :zap: update imports

---

package-lock.json
package.json
src/machine-identifier/machine-identifier.service.ts

docs: :bug: update tipes

---

src/cashier-session/cashier-session.service.ts
src/clousures-of-operations/clousures-of-operations.service.ts
src/libs/pdfKit.ts
src/tables/tables.controller.ts
src/tables/tables.service.ts

perf: :zap: joinTables with bill enable

---

src/app.module.ts
src/dto/reopen/createReopen.ts
src/process/process.service.ts
src/reopen/reopen.controller.ts
src/reopen/reopen.module.ts
src/reopen/reopen.service.ts
src/schemas/reopen/reopen.schema.ts
src/schemas/ventas/payment.schema.ts
src/ventas/payments/payments.controller.ts
src/ventas/payments/payments.service.ts

Updates changes semana 18/10/2024
Updates changes semana 18/10/2024

test: :sparkles: Updates changes semana 18/10/2024

---

src/cashier-session/cashier-session.controller.ts
src/cashier-session/cashier-session.service.ts
src/dto/cashierSession/cashWithdraw/createCashWithdraw.ts
src/dto/cashierSession/cashWithdraw/updateCashWithdraw.ts
src/schemas/cashierSession/cashWithdraw.ts
src/schemas/ventas/cancellations.schema.ts
src/ventas/bills/bills.service.ts
src/ventas/cancellations/cancellations.controller.ts
src/ventas/cancellations/cancellations.service.ts
src/ventas/discounts/discounts.controller.ts
src/ventas/discounts/discounts.service.ts
src/ventas/payments/payments.controller.ts
src/ventas/payments/payments.service.ts

updatesa week 41
updatesa week 41

docs: :memo: updatesa week 41

---

src/business/business.controller.ts
src/business/business.service.ts
src/device/device.controller.ts
src/device/device.module.ts
src/device/device.service.ts
src/dto/devices/createDeviceDto.ts
src/dto/devices/updateDeviceDto.ts
src/schemas/business/branchSchema.ts
src/schemas/business/licenseKeySchema.ts
src/schemas/devices/device.schema.ts
src/schemas/setting/setting.schema.ts

perf: :ambulance: update

---

.vscode/settings.json
src/additions-group/additions-group.controller.ts
src/additions-group/additions-group.module.ts
src/additions-group/additions-group.service.ts
src/app.module.ts
src/daily-register/daily-register.controller.ts
src/daily-register/daily-register.service.ts
src/schemas/catalogo/additions.schema.ts
src/schemas/dailyRegister/createDailyRegister.ts

test: :bug: updates

---

src/additions-group/additions-group.controller.ts
src/additions-group/additions-group.service.ts
src/catalogo/products/products.service.ts
src/daily-register/daily-register.controller.ts
src/daily-register/daily-register.service.ts
src/dto/catalogo/products/createProduct.dto.ts
src/dto/catalogo/products/updatedProduct.dto.ts
src/dto/dailyRegister/updateDailyRegister.dto.ts
src/schemas/catalogo/products.schema.ts
src/schemas/ventas/product.schema.ts
src/ventas/discounts/discounts.service.ts

update week 11/22/2024
update week 11/22/2024

test: :ambulance: update week 11/22/2024

---

src/auth/auth.service.ts

perf: :ambulance: update server

---

.vscode/settings.json
src/catalogo/dishes/dishes.controller.ts
src/catalogo/dishes/dishes.service.ts
src/catalogo/modifications/modifications.controller.ts
src/clousures-of-operations/clousures-of-operations.service.ts
src/dto/catalogo/dishes/createdDishes.dto.ts
src/dto/catalogo/dishes/updatedDishes.dto.ts
src/schemas/catalogo/dishes.schema.ts
src/utils/business/CalculateTotals.ts
src/ventas/payments/payments.service.ts

update changes week 06/12/2024
update changes week 06/12/2024

feat(update changes week 06/12/2024): update changes week 06/12/2024

---

package-lock.json
package.json
src/clousures-of-operations/clousures-of-operations.service.ts
src/device/device.controller.ts
src/device/device.service.ts
src/dto/devices/updateDeviceDto.ts
src/schemas/devices/device.schema.ts
src/setting/setting.controller.ts
src/setting/setting.service.ts
src/ventas/payments/payments.service.ts

update server for the printer configs
update server for the printer configs

test: :sparkles: update server for the printer configs

---

src/setting/setting.service.ts

refactor: :bug: Fix server

---

src/business/business.service.ts

test(update changes week 06/12/2024): :bug: last changes

---

src/daily-register/daily-register.service.ts
src/device/device.service.ts

perf: :bug: updatechanges

---

src/daily-register/daily-register.service.ts

refresh server for the new vcersion pos
refresh server for the new vcersion pos

perf: :ambulance: refresh server for the new vcersion pos

---

src/device/device.service.ts

test: :sparkles: last changes

---

src/config/printers/printers.controller.ts
src/device/device.service.ts
src/schemas/configuracion/printer.schema.ts

update changes latest
update changes latest

test: :sparkles: update changes latest

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/config/printers/printers.controller.ts
src/cron/cron.service.ts
src/tables/tables.controller.ts
src/usuarios/profiles/profiles.service.ts
src/ventas/discounts/discounts.controller.ts
src/ventas/discounts/discounts.service.ts

Te comparto el link de pago, estará habilitado hasta las 23:59
Te comparto el link de pago, estará habilitado hasta las 23:59

build: :bug: fixed period problems

---

src/cron/cron.service.ts
src/dto/usuarios/profiles/updateProfileDto.ts
src/usuarios/profiles/profiles.controller.ts
src/usuarios/profiles/profiles.service.ts
src/ventas/discounts/discounts.service.ts

perf(server repair): :bug: update server

---

src/app.module.ts
src/cron/cron.service.ts
src/ventas/discounts/discounts.service.ts

Migrate to CosmosDB
Migrate to CosmosDB

refactor(server repair): :zap: Migrate to CosmosDB

---

src/dto/catalogo/modifiers/createModifierDto.ts
src/dto/catalogo/modifiers/updateModifierDto.ts
src/schemas/catalogo/modifiers.Schema.ts

test: :bug: add verbs in modifiers

---

src/clousures-of-operations/clousures-of-operations.service.ts
src/clousures-of-operations/lib/calculateTotalByType.ts

test: :bug: uipdate server

---

src/clousures-of-operations/clousures-of-operations.service.ts

build: :memo: new summary cashier

---

src/clousures-of-operations/clousures-of-operations.service.ts

new implementation
new implementation

build: :zap: new implementation

---

src/clousures-of-operations/clousures-of-operations.service.ts
src/tables/tables.service.ts
src/ventas/bills/bills.controller.ts

test: :sparkles: discount features

---

src/ventas/discounts/discounts.controller.ts
src/ventas/discounts/discounts.service.ts

build: :memo: updates

---

src/ventas/discounts/discounts.service.ts

fix courtesy notes response
fix courtesy notes response

build: :sparkles: fix courtesy notes response

---

src/clousures-of-operations/clousures-of-operations.service.ts
src/cron/cron.service.ts
src/ventas/discounts/discounts.service.ts

calculate accouonts
calculate accouonts

refactor(update changes week 06/12/2024): :zap: calculate accouonts

---

src/clousures-of-operations/clousures-of-operations.controller.ts
src/clousures-of-operations/clousures-of-operations.service.ts

feat(update changes week 06/12/2024): new freatures

---

src/clousures-of-operations/clousures-of-operations.controller.ts
src/clousures-of-operations/clousures-of-operations.module.ts
src/clousures-of-operations/clousures-of-operations.service.ts

test: :fire: latest

---

src/clousures-of-operations/lib/calculateTotalByType.ts

test: :bug: latest changes

---

.vscode/settings.json
src/ventas/bills/bills.service.ts

feat(update server): update server

---

src/cashier-session/cashier-session.service.ts
src/process/process.service.ts
src/ventas/bills/bills.service.ts
src/ventas/payments/payments.service.ts

ci: :fire: last changes

---

src/ventas/payments/payments.service.ts

perf(update changes week 06/12/2024): :ambulance: update server

---

src/dto/reopen/createReopen.ts
src/process/process.service.ts
src/reopen/reopen.controller.ts
src/reopen/reopen.module.ts
src/reopen/reopen.service.ts
src/schemas/reopen/reopen.schema.ts
src/ventas/bills/bills.service.ts
src/ventas/payments/payments.service.ts

perf(server repair): :sparkles: server repair

---

src/ventas/notes/notes.service.ts

ci(server repair): :lipstick: update backend

---

src/cron/cron.controller.ts
src/cron/cron.service.ts
src/operating-period/operating-period.service.ts
src/process/process.service.ts
src/ventas/bills/bills.service.ts
src/ventas/notes/notes.service.ts

refactor(update server): :fire: new changes

---

src/cron/cron.service.ts
src/operating-period/operating-period.service.ts
src/ventas/bills/bills.service.ts
src/ventas/cancellations/cancellations.service.ts
src/ventas/notes/notes.service.ts

build: :ambulance: update server

---

src/clousures-of-operations/clousures-of-operations.service.ts
src/process/process.service.ts
src/reports/reports.controller.ts
src/reports/reports.service.ts
src/ventas/bills/bills.controller.ts

test: :ambulance: refresh server

---

src/ventas/cancellations/cancellations.service.ts

refresh changes
refresh changes

build: :sparkles: refresh changes

---

src/ventas/cancellations/cancellations.service.ts
src/ventas/payments/payments.service.ts

test: :bug: fix server

---

package.json
scripts/copyBinFiles.js
src/lib/calculateTotals.ts
src/operating-period/operating-period.service.ts
src/process/process.service.ts
src/reports/reports.controller.ts
src/reports/reports.module.ts
src/reports/reports.service.ts
src/scripts/copyBinFiles.js
src/ventas/payments/payments.service.ts
tsconfig.json

update servidor
update servidor

perf: :fire: update servidor

---

src/libs/formatToCurrency.ts
src/operating-period/operating-period.service.ts
src/process/process.service.ts
src/schemas/operatingPeriod/operationalClousure.ts
src/ventas/cancellations/cancellations.service.ts
src/ventas/payments/payments.service.ts

perf: :ambulance: update changes

---

src/dto/ventas/orders/phoneOrder/createPhoneOrder.dto.ts
src/operating-period/operating-period.module.ts
src/operating-period/operating-period.service.ts
src/reports/lib/calculateTimes.ts
src/reports/reports.controller.ts
src/reports/reports.service.ts
src/schemas/ventas/orders/toGoOrder.schema.ts
src/ventas/bills/bills.service.ts
src/ventas/discounts/discounts.controller.ts
src/ventas/discounts/discounts.service.ts

perf(update server): :ambulance: update server

---

src/daily-register/daily-register.service.ts

perf: :bug: update server

---

src/cron/cron.controller.ts
src/cron/cron.service.ts
src/operating-period/operating-period.service.ts
src/ventas/bills/bills.service.ts

populate paymenty
populate paymenty

test: :bug: populate paymenty

---

src/cashier-session/cashier-session.controller.ts
src/cashier-session/cashier-session.service.ts
src/catalogo/products/products.service.ts
src/operating-period/operating-period.service.ts
src/ventas/cancellations/cancellations.service.ts

update week 18/04/2025
update week 18/04/2025

build: update week 18/04/2025

---

src/ventas/cancellations/cancellations.service.ts

last changes 18/04/2025
last changes 18/04/2025

build: :ambulance: last changes 18/04/2025

---

src/operating-period/operating-period.service.ts

build(update server): :zap: 21/04/25

---

src/operating-period/operating-period.service.ts
src/schemas/SourcePeriod/sourcePeriod.schema.ts

refactor(update server): :fire: 23/04/2025

---

src/app.module.ts
src/operating-period/operating-period.service.ts
src/rewrite-period/rewrite-period.controller.ts
src/rewrite-period/rewrite-period.module.ts
src/rewrite-period/rewrite-period.service.ts
src/schemas/RewritedPeriod/rewritedPeriod.ts
src/schemas/operatingPeriod/operatingPeriod.schema.ts

test(update server): :fire: hot reload

---

src/rewrite-period/rewrite-period.controller.ts
src/rewrite-period/rewrite-period.module.ts
src/rewrite-period/rewrite-period.service.ts

update server with rewrite period functions
update server with rewrite period functions

refactor: :ambulance: update server with rewrite period functions

---

src/ventas/discounts/discounts.service.ts

Fix bills courtesies
Fix bills courtesies

build: :fire: Fix bills courtesies
